# Generated by Django 2.2 on 2019-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temprature_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=10)),
                ('temprature', models.FloatField()),
                ('date_received', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
